<?php /* Smarty version Smarty-3.1.11, created on 2012-07-03 15:16:45
         compiled from "C:\Users\Reky nala\Desktop\add-mvc-framework\branches\0.6\views\common_footer.tpl" */ ?>
<?php /*%%SmartyHeaderCode:35584ff30cdd1a2e33-30456439%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '5b525eff39506511541e1e8b7a5394b1bd7e7948' => 
    array (
      0 => 'C:\\Users\\Reky nala\\Desktop\\add-mvc-framework\\branches\\0.6\\views\\common_footer.tpl',
      1 => 1341327589,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '35584ff30cdd1a2e33-30456439',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.11',
  'unifunc' => 'content_4ff30cdd1b5ca8_85025784',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_4ff30cdd1b5ca8_85025784')) {function content_4ff30cdd1b5ca8_85025784($_smarty_tpl) {?>
         </div>
         <div id="footer">
            <div class="generator">
               Generated by ADD MVC Framework
            </div>
         </div>
      </div>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
      
      <script type="text/javascript">
         $('*[data-href]').click(
               function() {
                  location.href = $(this).attr('data-href');
               }
            );
      </script>
      

   </body>
</html><?php }} ?>