{block name="response"}
{if add::content_type() == "text/plain"}{*
* Plain text layout
*}
{block name=header}{block name=meta_title}{/block}{/block}

{block name=main}{/block}
{block name=footer}{/block}

{else}
<!DOCTYPE html>
<html>
   <head>

{block name=metas}
      <title>{block name=meta_title}{/block}</title>
      <meta name="description" content="{block name=meta_description}{/block}" />
      <meta name="keywords" content="{block name=meta_keywords}{/block}" />
{/block}

{block name=styles}
      <link href="//add-presentability.googlecode.com/svn/project/trunk/all.css" rel="stylesheet" type="text/css" />
{/block}

{block name=head_scripts}{/block}
   </head>
   <body class="{$ctrl_basename|escape} mode_{$mode|escape}">
      <div class="page"  itemscope itemtype="http://schema.org/WebPage">

{block name=header}
         <div class="header"  itemscope itemtype="http://schema.org/WPHeader">
            <a href="{add::config()->base_url}" class="title">
               {add::config()->super_domain|upper}
            </a>
         </div>
         <nav itemscope itemtype="http://schema.org/SiteNavigationElement">
            {block name='nav'}
            <ul>
               <li><a href="{add::config()->base_url}">Home</a></li>
            </ul>
            {/block}
         </nav>
{/block}
         <div class="main" itemprop="mainContentOfPage">
{block name=main}{/block}
         </div>
         <div class="footer" itemscope itemtype="http://schema.org/WPFooter">
            <div class="generator">
               Generated by ADD MVC Framework
            </div>
         </div>
      </div>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

      {block name=post_body_scripts}
      <script src="https://add-usability.googlecode.com/svn/project/trunk/js/all.js"></script>
      {/block}

   </body>
</html>
{/if}
{/block}