<?php /* Smarty version Smarty-3.1.8, created on 2012-07-02 22:19:17
         compiled from "../../trunk/views\common_footer.tpl" */ ?>
<?php /*%%SmartyHeaderCode:64404ff21e654d7103-92594422%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'c207e8551f1fe9e13dfd239e1fc1d145757698f9' => 
    array (
      0 => '../../trunk/views\\common_footer.tpl',
      1 => 1340299515,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '64404ff21e654d7103-92594422',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.8',
  'unifunc' => 'content_4ff21e654e7f28_84011500',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_4ff21e654e7f28_84011500')) {function content_4ff21e654e7f28_84011500($_smarty_tpl) {?>
         </div>
         <div id="footer">
            <div class="generator">
               Generated by ADD MVC Framework
            </div>
         </div>
      </div>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
      
      <script type="text/javascript">
         $('*[data-href]').click(
               function() {
                  location.href = $(this).attr('data-href');
               }
            );
      </script>
      

   </body>
</html><?php }} ?>